#@baseURL = http://localhost:5227/api
@baseURL = http://localhost:8080/api

### Get all Platforms
GET {{baseURL}}/Platforms

### Get single Platform
GET {{baseURL}}/Platforms/5

### Create Platform
POST http://localhost:5227/api/Platforms
accept: text/plain
Content-Type: application/json

{
  "Name": "Go",
  "Publisher": "Google",
  "Cost": "Free"
}

### Update Platform
PUT {{baseURL}}/Platforms/4
accept: text/plain
Content-Type: application/json

{
  "Name": "Go4",
  "Publisher": "Google"
}

### Delete Platform
DELETE {{baseURL}}/Platforms/5
