### Local
@baseURL = https://localhost:7000/api/c/Platforms

### Docker
#@baseURL = https://localhost:8080/api/c/Platforms

### Kubernetes
#@baseURL = https://localhost:32484/api/c/Platforms

### Get Commands for Platform
GET {{baseURL}}/5/commands

### Get Command for Platform
GET {{baseURL}}/5/commands/1

### Create Command for Platform
POST {{baseURL}}/5/commands
Content-Type: application/json

{
    "HowTo": "Push to Docker Hub",
    "CommandLine": "docker push <Name of the container>"
}