### Local
#@baseURL = https://localhost:7000/api/c/Platforms

### Docker
#@baseURL = https://localhost:8080/api/c/Platforms

### Kubernetes
#@baseURL = https://localhost:32484/api/c/Platforms

### Get Commands for Platform
GET {{baseURL}}/1/commands